import ccxt
import pandas as pd
import numpy as np
from ta.momentum import RSIIndicator, StochasticOscillator
from ta.trend import MACD, SMAIndicator
from ta.volatility import BollingerBands, AverageTrueRange
from sklearn.preprocessing import StandardScaler
import joblib
import time
import os

# Configuration
SYMBOL = 'BTC/USDT'
TIMEFRAME = '15m'
LIMIT = 1000 # Max per request on Bybit is 1000
TOTAL_CANDLES = 15000 # Roughly 156 days of 15m data

def fetch_historical_data(symbol, timeframe, total_candles):
    print(f"Fetching {total_candles} candles of {symbol} at {timeframe}...")
    exchange = ccxt.bybit({'enableRateLimit': True})
    
    all_ohlcv = []
    since = exchange.milliseconds() - total_candles * 15 * 60 * 1000 # Approx start time
    
    while len(all_ohlcv) < total_candles:
        try:
            ohlcv = exchange.fetch_ohlcv(symbol, timeframe, since=since, limit=LIMIT)
            if len(ohlcv) == 0:
                break
            since = ohlcv[-1][0] + 1
            all_ohlcv.extend(ohlcv)
            print(f"Fetched {len(all_ohlcv)}/{total_candles}")
            time.sleep(exchange.rateLimit / 1000)
        except Exception as e:
            print(f"Error fetching data: {e}")
            time.sleep(5)
            
    df = pd.DataFrame(all_ohlcv, columns=['timestamp', 'open', 'high', 'low', 'close', 'volume'])
    df['timestamp'] = pd.to_datetime(df['timestamp'], unit='ms')
    df.set_index('timestamp', inplace=True)
    
    # Drop duplicates if any
    df = df[~df.index.duplicated(keep='first')]
    return df

def feature_engineering(df):
    print("Applying feature engineering...")
    
    # Log Returns
    df['log_return'] = np.log(df['close'] / df['close'].shift(1))
    
    # RSI
    df['rsi'] = RSIIndicator(close=df['close'], window=14).rsi()
    
    # MACD
    macd = MACD(close=df['close'])
    df['macd'] = macd.macd()
    df['macd_signal'] = macd.macd_signal()
    df['macd_diff'] = macd.macd_diff()
    
    # SMAs and Distances
    for period in [20, 50, 200]:
        df[f'sma_{period}'] = SMAIndicator(close=df['close'], window=period).sma_indicator()
        df[f'dist_sma_{period}'] = (df['close'] - df[f'sma_{period}']) / df[f'sma_{period}']
        
    # Bollinger Bands
    bb = BollingerBands(close=df['close'], window=20, window_dev=2)
    df['bb_hband'] = bb.bollinger_hband()
    df['bb_lband'] = bb.bollinger_lband()
    df['bb_width'] = bb.bollinger_wband()
    df['bb_percent'] = bb.bollinger_pband()
    
    # ATR
    df['atr'] = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'], window=14).average_true_range()
    
    # Volume features
    df['volume_sma_20'] = df['volume'].rolling(window=20).mean()
    df['volume_ratio'] = df['volume'] / df['volume_sma_20']
    
    return df

def create_labels(df, lookahead=4, threshold=0.003):
    print(f"Creating labels with lookahead {lookahead} and threshold {threshold*100}%...")
    # Return over the next 'lookahead' candles
    # close(t + lookahead) / close(t) - 1
    future_return = (df['close'].shift(-lookahead) - df['close']) / df['close']
    
    # 1: Buy (future return >= 0)
    # 0: Sell (future return < 0)
    
    conditions = [
        (future_return >= 0),
        (future_return < 0)
    ]
    choices = [1, 0]
    df['label'] = np.select(conditions, choices, default=0)
    
    # We must drop rows with NaN values generated by shifting and indicators
    df.dropna(inplace=True)
    return df

def scale_and_save(df):
    print("Scaling features and saving...")
    
    features = [
        'log_return', 'rsi', 'macd', 'macd_signal', 'macd_diff',
        'dist_sma_20', 'dist_sma_50', 'dist_sma_200',
        'bb_width', 'bb_percent', 'atr', 'volume_ratio'
    ]
    
    scaler = StandardScaler()
    df_scaled = df.copy()
    
    # Fit and transform
    df_scaled[features] = scaler.fit_transform(df[features])
    
    # Save scaler
    os.makedirs('models', exist_ok=True)
    joblib.dump(scaler, 'models/scaler.pkl')
    
    # Save dataset
    df_scaled.to_csv('dataset.csv')
    print(f"Dataset saved with shape: {df_scaled.shape}")
    
    # Print label distribution
    print("Label distribution:")
    print(df_scaled['label'].value_counts(normalize=True))

if __name__ == "__main__":
    df_raw = fetch_historical_data(SYMBOL, TIMEFRAME, TOTAL_CANDLES)
    df_features = feature_engineering(df_raw)
    df_labeled = create_labels(df_features)
    scale_and_save(df_labeled)
    print("Phase 1 completed!")
